name: rwanda-logistics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - osmnx=1.9
  - networkx=3.2
  - geopandas=0.14
  - folium=0.15
  - scipy=1.11
  - numpy=1.26
  - matplotlib=3.8
  - seaborn=0.13
  - jupyterlab=4.0
  - pip:
    - ortools==9.8.3296
    - numba==0.58
